.PHONY: warn
warn:
	@echo 'Run'
	@echo '    make install-homebrew'
	@echo '    make install-packages'

.PHONY: install-homebrew
install-homebrew:
	/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

.PHONY: install-packages
install-packages:
	brew install skopeo
	brew install linode-cli
# 	brew install doctl
# 	brew install awscli
# 	brew install azure-cli
	brew install python@3.14
	brew install git
	brew install fzf
# 	brew install kubectx
# 	brew install kubernetes-cli
	brew install direnv
# 	brew install tfenv
# 	brew install rbtools
	brew install jq
	brew install yq
	brew install opentofu
	brew install osc
	brew install uv
	brew install tree
	brew install xz
	brew install gawk
	brew install go
	brew install ansible
# 	brew install exercism
