.PHONY: warn
warn:
	@echo 'Run'
	@echo '    make install-ports'

.PHONY: install-ports
install-ports:
	brew install skopeo
	brew install awscli
	brew install azure-cli
	brew install python@3.9
	brew install git
	brew install fzf
	brew install kubectx
	brew install kubernetes-cli
	brew install direnv
	brew install tfenv
	brew install rbtools
	brew install jq
	brew install yq
