export CLICOLOR
CLICOLOR=1

if [ $ITERM_SESSION_ID ]; then
  export PROMPT_COMMAND='echo -ne "\033]0;${PWD/#$HOME/~}\007"'
fi

export GIT_PS1_SHOWUPSTREAM
GIT_PS1_SHOWUPSTREAM='verbose name'
export GIT_PS1_SHOWDIRTYSTATE
GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE
GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES
GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM
GIT_PS1_SHOWUPSTREAM=auto
export GIT_PS1_DESCRIBE_STYLE
GIT_PS1_DESCRIBE_STYLE=default
export GIT_PS1_SHOWCOLORHINTS
GIT_PS1_SHOWCOLORHINTS=true
export GIT_PS1_HIDE_IF_PWD_IGNORED
GIT_PS1_HIDE_IF_PWD_IGNORED=true
. ~/.git-prompt.sh

export PS1
if [ "$TERM" = xterm-256color ]; then
    PS1='\[\033[01;32m\]\w$(__git_ps1 " git->(%s)") $\[\e[0m\] '
else
    PS1='\t \w$(__git_ps1 " git->(%s)") $ '
fi

##
# Your previous /Users/CHANGEME/.bash_profile file was backed up as /Users/CHANGEME/.bash_profile.macports-saved_2018-01-22_at_15:48:14
##

# MacPorts Installer addition on 2018-01-22_at_15:48:14: adding an appropriate PATH variable for use with MacPorts.
export PATH="/opt/local/bin:/opt/local/sbin:$PATH"
# Finished adapting your PATH environment variable for use with MacPorts.

